# Generated by Django 5.0 on 2023-12-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0002_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='container',
            field=models.ForeignKey(default='cd2df616-3410-421a-b0b6-7d249722e3a3', on_delete=django.db.models.deletion.CASCADE, to='mms_api.container'),
            preserve_default=False,
        ),
    ]
